name: Update Service Worker Version

on:
  push:
    branches:
      - main

jobs:
  update-service-worker:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Generate new cache version
        run: |
          VERSION=$(git rev-parse --short HEAD)
          SW_FILE="sw.js"
          sed -i "s/const cacheVersion = \".*\";/const cacheVersion = \"${VERSION}\";/" $SW_FILE

      - name: Commit updated service worker
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          git add sw.js
          git commit -m "Update service worker version to ${VERSION}"
          git push
